package main

import (
	"encoding/json"
	"fmt"
	"log"
	"math"
	"net/http"
	"strconv"
	"strings"
)

func main() {
	fmt.Println("hejsa")

	res, err := http.Get("https://static.editorialdev.tv2a.dk/assets/2020/covid19/vaccinesDashboard.json")
	if err != nil {
		log.Fatal("Unable to get data")
	}

	var result AutoGenerated
	err = json.NewDecoder(res.Body).Decode(&result)
	if err != nil {
		log.Fatalf("Unable to decode data: %v", err)
		return
	}

	fix_number := strings.Replace(result.Danmark.Vaccinedoneper100, ",", ".", -1)
	number, err := strconv.ParseFloat(fix_number, 64)
	if err != nil {
		log.Fatalf("Unable to parse number to float: %v", err)
	}

	fmt.Println(createProgressBar(number))
}

func createProgressBar(number float64) string {
	var result string

	solids := int(math.Floor(number * 15 / 100))
	emptys := 15 - solids

	for i := 0; i < solids; i++ {

		result = result + "▓"
	}
	for i := 0; i < emptys; i++ {

		result = result + "░"
	}

	return fmt.Sprintf("%s %.2f%%", result, number)
}

type AutoGenerated struct {
	Danmark struct {
		Vaccinestarted       string `json:"vaccinestarted"`
		Vaccinestartedper100 string `json:"vaccinestartedper100"`
		Vaccinedone          string `json:"vaccinedone"`
		Vaccinedoneper100    string `json:"vaccinedoneper100"`
		Dosestotal           string `json:"dosestotal"`
		Dosestotalper100     string `json:"dosestotalper100"`
		Dosesdaily           string `json:"dosesdaily"`
		Updated              string `json:"updated"`
	} `json:"Danmark"`
	World struct {
		Vaccinestarted        string `json:"vaccinestarted"`
		Vaccinestartedper100  string `json:"vaccinestartedper100"`
		Fullyvaccinated       string `json:"fullyvaccinated"`
		Fullyvaccinatedper100 string `json:"fullyvaccinatedper100"`
		Updated               string `json:"updated"`
	} `json:"World"`
	Disclaimer string `json:"disclaimer"`
}
