version: 2.1

jobs:
  tweet:
    docker:
      - image: cimg/go:1.16.3
    steps:
      - checkout
      - run:
          name: go get
          command: go get ./...
      - run:
          name: Run it !
          command: |
            go run main.go

workflows:
  manual:
    when: << pipeline.parameters.run_manually >>
    jobs:
      - tweet

  nightly:
    triggers:
      - schedule:
          cron: "0 13 * * *"
          filters:
            branches:
              only: master
    jobs:
      - tweet

parameters:
  run_manually:
    type: boolean
    default: false